### ISSUE TITLE
build/release process

### ISSUE THREAD

**Issue by skibz** [CyrisXD/SteamRoller-Steam-Quick-Launcher#10]
i'm in the process of revamping the app manifests (package.json, or whatever) in order to make development more comfortable and building releases for different platforms easier.

**Comment by Rock48** [comment]
Neat; My IDE - RubyMine - Has built-in support for running and debugging node-webkit apps, as well as building for all operating systems. If this makes it easier for others though sounds like a great idea.

**Comment by skibz** [comment]
rubymine, interesting. i've never looked at it before, but i will be sure to check it out soon if it offers that kind of a toolchain.

ideally, i plan on including node-webkit-builder as a dev dependency. it caught my eye because its able to build releases for all platforms, run built releases for dev/testing _and_ expose an api.

**Comment by skibz** [comment]
have opened [this](https://github.com/CyrisXD/SteamRoller-Steam-Quick-Launcher/pull/11)
work in progress as it's still missing the release builder, though.

**Comment by CyrisXD** [comment]
Good work guys, just a little busy so only skimmed through. Will have a proper run through and merge on the weekend.
