### ISSUE TITLE
Hover scrolling continues when leaving

### ISSUE THREAD

**Issue by LucaBastelt** [CyrisXD/SteamRoller-Steam-Quick-Launcher#2]
When leaving the hover-scroll area directly to a window, it keeps scrolling.
![bug](https://cloud.githubusercontent.com/assets/924818/6203081/ebbeec6a-b50d-11e4-9a93-e22aea8bb31d.PNG)

**Comment by LucaBastelt** [comment]
The same problem occurs when leaving the area to the task-bar.

**Comment by LucaBastelt** [comment]
Turns out it only stops scrolling when the mouse leaves over the the middle part of the widget.

**Comment by Rock48** [comment]
This is a limitation of node-webkit, sorry, so unless Cyris develops code wizard powers this will be difficult to fix.

**Comment by LucaBastelt** [comment]
Sure? I thought a small border would solve that, wouldn't it?

**Comment by Rock48** [comment]
hang on-- I'll play with some code

**Comment by Rock48** [comment]
Alright, I've hacked together a fix, it's not super pretty but I think it should work. Are you comfortable downloading my fork and running it with node-webkit? If not, I'll throw an exe together for you to test it.

**Comment by LucaBastelt** [comment]
I don't know how to do the fork thing, sorry. But I can test an exe (=

**Comment by Rock48** [comment]
Alright, I'll put it together

**Comment by Rock48** [comment]
[Hopefully this works](https://dl.dropboxusercontent.com/u/42055532/SteamRoller64-RocksFork.zip), if it does, I'll request a merge with Cyris's branch

**Comment by LucaBastelt** [comment]
Ok, it works  but the re-sizing seems to be broken now.
Also it only works for the sides and not for the top.

**Comment by Rock48** [comment]
Making it work for top and bottom would be a nightmare, also, what do you mean by re-sizing is broken.

**Comment by Rock48** [comment]
By nightmare I mean the only way to fix it would be to make it look incredibly ugly.

**Comment by LucaBastelt** [comment]
Its not that bad so I guess a fix is no must have ^^
Resizing the area is broken. The resize cursor is shown but using it doesn't do anything.

**Comment by Rock48** [comment]
Huh, weird, it never worked for me, just noticed that it worked on the last version, but it didn't work at all when running from source. Hang on.

**Comment by Rock48** [comment]
Hmm, it seems I'm using a slightly different version of node-webkit, I'm gonna try and make and exe with the version that Cyris is using.

**Comment by Rock48** [comment]
Yep! The lastest version of node-webkit seems to totally break resizing that window, nw 0.11.6 works though. [This one _should_ work](https://dl.dropboxusercontent.com/u/42055532/SteamRoller64-Rock.zip)

**Comment by LucaBastelt** [comment]
My download speed has decreased to 50kb/s ^^ Give me a second to download

**Comment by LucaBastelt** [comment]
It works (=

**Comment by Rock48** [comment]
Yay, submitting pull request now.

**Comment by CyrisXD** [comment]
Good work guys. More tweaks coming soon.
