### ISSUE TITLE
Settings CSS

### ISSUE THREAD

**Issue by TheDrDocter** [CyrisXD/SteamRoller-Steam-Quick-Launcher#23]
I am currently working on a CSS stylesheet code to make the 'save' button for the setting/change user thing look good.

**Comment by odensc** [comment]
What exactly is this for?

**Comment by TheDrDocter** [comment]
When you click the gear and the text box pops up with the default button type. I wanna change that, yaknow for aesthetic purposes and such.

**Comment by TheDrDocter** [comment]
@thesbros This forum/issue is mainly for discussing any other ideas we want for the program in the future I guess.

**Comment by odensc** [comment]
@TheDrDocter We already have the feedback issue.

**Comment by TheDrDocter** [comment]
I see. _Loads Gun_

**Comment by odensc** [comment]
#25
