### ISSUE TITLE
Opacity breaks

### ISSUE THREAD

**Issue by EchoDel** [CyrisXD/SteamRoller-Steam-Quick-Launcher#4]
When running steam roller, then launching final fantasy 13 or 13-2, returning to the desktop causes steam roller to have a black background.

![steamroller1](https://cloud.githubusercontent.com/assets/2352735/6236685/8f47eb0c-b6e4-11e4-92b4-7f25a6a37667.png)
![steamroller2](https://cloud.githubusercontent.com/assets/2352735/6236686/8f652140-b6e4-11e4-9730-5058e80c97e0.png)

**Comment by Rock48** [comment]
I had this happen to me when I left my computer on over night; the next day the window was totally opaque. Although likely a bug with node-webkit, I'll let Cyris look into this one, that's his domain.

**Comment by CyrisXD** [comment]
Thanks for the report and screenshots, I'll have a look into a fix but I'm learning towards a Node-Webkit bug. They have only just recently enabled transparency. I'll keep trying with newer versions of Node-Webkit as they are released.
