### ISSUE TITLE
SteamRoller duplicating multiple games

### ISSUE THREAD

**Issue by NanoDrivee** [CyrisXD/SteamRoller-Steam-Quick-Launcher#6]
For some reason it seems to be duplicating every game in my library.
![sxfvjom](https://cloud.githubusercontent.com/assets/10505006/6257537/b2f27d88-b775-11e4-9e98-d0e52ebe6c0d.png)

Specs:
Windows 8.1 64-bit

**Comment by skibz** [comment]
@SuperLemrick , you really ought to provide more information about your issue.

**Comment by SuperLemrick** [comment]
Like what? I am not really sure what else to provide. I will put

**Comment by NanoDrivee** [comment]
It fixed it self, I feel kind of dumb now. Sorry for the hassle.

**Comment by CyrisXD** [comment]
This may be happening if users double click the 'submit' button when inserting their usernames.
